env_name                      = "dev"
app_name                      = "ror"
region                        = "ap-south-1"
availability_zones            = ["ap-south-1a", "ap-south-1b", "ap-south-1c"]
enable_nat_gateway            = true
single_nat_gateway            = true
bastion_instance_type         = "t3.nano"
domain_name                   = "rordeployment.com"
admin_domain_name             = "admin"
common_tags                   = { "environment" : "dev" }
db_engine                     = "aurora-postgresql"
db_engine_version             = "13.9"
db_instance_type              = "db.t3.medium"
db_username                   = "dbadmin"
database_name                  = "ror"
db_port                       = 5432
db_backup_retention_period    = 5
db_autoscaling_min_capacity   = 1
db_autoscaling_max_capacity   = 1
ami_instance_type             = "t3.nano"
ami_name                      = ["amzn2-ami-hvm-*-x86_64-gp2"]
autoscalling_min_size         = 0
autoscalling_max_size         = 1
autoscalling_desired_capacity = 1
ecs_cpu                       = "512"
ecs_memory                    = "1024"
alert_email_addresses         = ["mkabil0210@gmail.com"]
elb_account_id                = "718504428378"
